# Generated by Django 4.1.4 on 2023-01-28 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('query_txt', models.TextField()),
                ('add_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '17. Contact Queries',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('date_start', models.DateField(null=True)),
                ('date_end', models.DateField(null=True)),
                ('description', models.TextField()),
                ('featured_img', models.ImageField(null=True, upload_to='event_imgs/')),
                ('event_views', models.BigIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': '3. Events',
            },
        ),
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': '2. Event Categories',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
            ],
            options={
                'verbose_name_plural': '16. FAQs',
            },
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile_no', models.CharField(max_length=20, null=True)),
                ('profile_img', models.ImageField(null=True, upload_to='organizer_profile_imgs/')),
                ('about_me', models.TextField()),
                ('verify_status', models.BooleanField(default=False)),
                ('otp_digit', models.CharField(max_length=10, null=True)),
                ('login_via_otp', models.BooleanField(default=False)),
                ('facebook_url', models.URLField(null=True)),
                ('linkedin_url', models.URLField(null=True)),
                ('instagram_url', models.URLField(null=True)),
                ('website_url', models.URLField(null=True)),
            ],
            options={
                'verbose_name_plural': '1. Organizers',
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('username', models.CharField(max_length=200)),
                ('interested_categories', models.TextField()),
                ('profile_img', models.ImageField(null=True, upload_to='participant_profile_imgs/')),
                ('verify_status', models.BooleanField(default=False)),
                ('otp_digit', models.CharField(max_length=10, null=True)),
                ('login_via_otp', models.BooleanField(default=False)),
                ('facebook_url', models.URLField(null=True)),
                ('linkedin_url', models.URLField(null=True)),
                ('instagram_url', models.URLField(null=True)),
                ('website_url', models.URLField(null=True)),
            ],
            options={
                'verbose_name_plural': '5. Participants',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('detail', models.TextField()),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('organizer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_api.organizer')),
            ],
            options={
                'verbose_name_plural': '11. Quiz',
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('video', models.FileField(null=True, upload_to='sponsor_videos/')),
                ('remarks', models.TextField(null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_sponsors', to='backend_api.event')),
            ],
            options={
                'verbose_name_plural': '4. Sponsors',
            },
        ),
        migrations.CreateModel(
            name='ScientificMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('upload', models.FileField(null=True, upload_to='scientific_materials/')),
                ('remarks', models.TextField(null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.event')),
            ],
            options={
                'verbose_name_plural': '15. Event Scientific Materials',
            },
        ),
        migrations.CreateModel(
            name='QuizQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.CharField(max_length=200)),
                ('ans1', models.CharField(max_length=200)),
                ('ans2', models.CharField(max_length=200)),
                ('ans3', models.CharField(max_length=200)),
                ('ans4', models.CharField(max_length=200)),
                ('right_ans', models.CharField(max_length=200)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_api.quiz')),
            ],
            options={
                'verbose_name_plural': '12. Quiz Questions',
            },
        ),
        migrations.CreateModel(
            name='ParticipantFavoriteEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.event')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.participant')),
            ],
            options={
                'verbose_name_plural': '7. Participant Favorite Events',
            },
        ),
        migrations.CreateModel(
            name='ParticipantEventEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_time', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_events', to='backend_api.event')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_participant', to='backend_api.participant')),
            ],
            options={
                'verbose_name_plural': '6. Enrolled Events',
            },
        ),
        migrations.CreateModel(
            name='ParticipantAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('detail', models.TextField(null=True)),
                ('participant_status', models.BooleanField(default=False, null=True)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('organizer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_api.organizer')),
                ('participant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_api.participant')),
            ],
            options={
                'verbose_name_plural': '9. Participant Assignments',
            },
        ),
        migrations.CreateModel(
            name='OrganizerParticipantChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_text', models.TextField()),
                ('msg_from', models.CharField(max_length=100)),
                ('msg_time', models.DateTimeField(auto_now_add=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.organizer')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.participant')),
            ],
            options={
                'verbose_name_plural': '18. Organizer Participant Messages',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_subject', models.CharField(max_length=200, null=True, verbose_name='Notification Subject')),
                ('notif_for', models.CharField(max_length=200, verbose_name='Notification For')),
                ('notif_created_time', models.DateTimeField(auto_now_add=True)),
                ('notifiread_status', models.BooleanField(default=False, verbose_name='Notification Status')),
                ('organizer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_api.organizer')),
                ('participant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_api.participant')),
            ],
            options={
                'verbose_name_plural': '10. Notifications',
            },
        ),
        migrations.CreateModel(
            name='EventRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveBigIntegerField(default=0)),
                ('reviews', models.TextField(null=True)),
                ('review_time', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_api.event')),
                ('participant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_api.participant')),
            ],
            options={
                'verbose_name_plural': '8. Event Ratings',
            },
        ),
        migrations.CreateModel(
            name='EventQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_api.event')),
                ('organizer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_api.organizer')),
                ('quiz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_api.quiz')),
            ],
            options={
                'verbose_name_plural': '13. Event Quiz',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_events', to='backend_api.eventcategory'),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizer_events', to='backend_api.organizer'),
        ),
        migrations.CreateModel(
            name='AttempQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right_ans', models.CharField(max_length=200, null=True)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_api.participant')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_api.quizquestions')),
                ('quiz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_api.quiz')),
            ],
            options={
                'verbose_name_plural': '14. Attempted Questions',
            },
        ),
    ]
