# Generated by Django 4.1.4 on 2023-01-29 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcategory',
            name='category_img',
            field=models.ImageField(null=True, upload_to='event_category_imgs/'),
        ),
    ]
